# This file was automatically generated by Vpl
write_user_impl_clock_constraint "level0_i/ulp" "clk_kernel2_in {is_user_set false instance _bd_top port clk_kernel2_in clk_id 1 freq 500.000000} clk_kernel_in {is_user_set true instance _bd_top port clk_kernel_in clk_id 0 freq 200}" "" "output"
