// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module config_parser_config_parser_Pipeline_VITIS_LOOP_207_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input1_V_TVALID,
        config_num,
        input1_V_TDATA,
        input1_V_TREADY,
        v1_buffer_V_address0,
        v1_buffer_V_ce0,
        v1_buffer_V_we0,
        v1_buffer_V_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   input1_V_TVALID;
input  [31:0] config_num;
input  [63:0] input1_V_TDATA;
output   input1_V_TREADY;
output  [7:0] v1_buffer_V_address0;
output   v1_buffer_V_ce0;
output   v1_buffer_V_we0;
output  [63:0] v1_buffer_V_d0;

reg ap_idle;
reg input1_V_TREADY;
reg v1_buffer_V_ce0;
reg v1_buffer_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln207_fu_76_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input1_V_TDATA_blk_n;
wire   [63:0] zext_ln207_fu_88_p1;
reg   [8:0] i_fu_34;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_2;
wire   [8:0] add_ln207_fu_82_p2;
wire   [31:0] zext_ln207_1_fu_72_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_100;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

config_parser_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_100)) begin
        if ((icmp_ln207_fu_76_p2 == 1'd0)) begin
            i_fu_34 <= add_ln207_fu_82_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_34 <= 9'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (icmp_ln207_fu_76_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_34;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln207_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_V_TDATA_blk_n = input1_V_TVALID;
    end else begin
        input1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (icmp_ln207_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        input1_V_TREADY = 1'b1;
    end else begin
        input1_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        v1_buffer_V_ce0 = 1'b1;
    end else begin
        v1_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (icmp_ln207_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v1_buffer_V_we0 = 1'b1;
    end else begin
        v1_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln207_fu_82_p2 = (ap_sig_allocacmp_i_2 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_100 = (~((ap_start_int == 1'b0) | ((icmp_ln207_fu_76_p2 == 1'd0) & (input1_V_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln207_fu_76_p2 = ((zext_ln207_1_fu_72_p1 == config_num) ? 1'b1 : 1'b0);

assign v1_buffer_V_address0 = zext_ln207_fu_88_p1;

assign v1_buffer_V_d0 = input1_V_TDATA;

assign zext_ln207_1_fu_72_p1 = ap_sig_allocacmp_i_2;

assign zext_ln207_fu_88_p1 = ap_sig_allocacmp_i_2;

endmodule //config_parser_config_parser_Pipeline_VITIS_LOOP_207_1
