// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="config_parser_config_parser,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.315925,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=713,HLS_SYN_LUT=6072,HLS_VERSION=2021_1}" *)

module config_parser (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input1_V_TDATA,
        input1_V_TVALID,
        input1_V_TREADY,
        input2_V_TDATA,
        input2_V_TVALID,
        input2_V_TREADY,
        output1_V_TDATA,
        output1_V_TVALID,
        output1_V_TREADY,
        output2_V_TDATA,
        output2_V_TVALID,
        output2_V_TREADY,
        output3_V_TDATA,
        output3_V_TVALID,
        output3_V_TREADY
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] input1_V_TDATA;
input   input1_V_TVALID;
output   input1_V_TREADY;
input  [511:0] input2_V_TDATA;
input   input2_V_TVALID;
output   input2_V_TREADY;
output  [63:0] output1_V_TDATA;
output   output1_V_TVALID;
input   output1_V_TREADY;
output  [31:0] output2_V_TDATA;
output   output2_V_TVALID;
input   output2_V_TREADY;
output  [63:0] output3_V_TDATA;
output   output3_V_TVALID;
input   output3_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input1_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    input2_V_TDATA_blk_n;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln227_fu_136_p2;
reg    output3_V_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [31:0] config_num_fu_107_p1;
reg   [31:0] config_num_reg_152;
wire   [31:0] data_num_fu_111_p1;
reg   [31:0] data_num_reg_161;
wire   [0:0] icmp_ln207_fu_115_p2;
wire   [63:0] zext_ln316_fu_120_p1;
wire   [63:0] zext_ln316_1_fu_129_p1;
reg   [511:0] tmp_reg_191;
reg   [7:0] v1_buffer_V_address0;
reg    v1_buffer_V_ce0;
reg    v1_buffer_V_we0;
wire   [63:0] v1_buffer_V_q0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_input1_V_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_ce0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_we0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_d0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TREADY;
wire   [7:0] grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_address0;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_ce0;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TVALID;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TREADY;
wire   [63:0] grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TVALID;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_done;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_idle;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_ready;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TREADY;
wire   [31:0] grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TDATA;
wire    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TVALID;
reg    grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg   [31:0] i_fu_54;
wire   [31:0] i_4_fu_141_p2;
reg    ap_block_state14;
reg    ap_block_state1;
wire    ap_CS_fsm_state17;
wire    regslice_both_output1_V_U_apdone_blk;
wire    regslice_both_output2_V_U_apdone_blk;
wire    regslice_both_output3_V_U_apdone_blk;
reg    ap_block_state17;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    regslice_both_input1_V_U_apdone_blk;
wire   [63:0] input1_V_TDATA_int_regslice;
wire    input1_V_TVALID_int_regslice;
reg    input1_V_TREADY_int_regslice;
wire    regslice_both_input1_V_U_ack_in;
wire    regslice_both_input2_V_U_apdone_blk;
wire   [511:0] input2_V_TDATA_int_regslice;
wire    input2_V_TVALID_int_regslice;
reg    input2_V_TREADY_int_regslice;
wire    regslice_both_input2_V_U_ack_in;
wire    output1_V_TREADY_int_regslice;
wire    regslice_both_output1_V_U_vld_out;
wire    output2_V_TREADY_int_regslice;
wire    regslice_both_output2_V_U_vld_out;
reg   [63:0] output3_V_TDATA_int_regslice;
reg    output3_V_TVALID_int_regslice;
wire    output3_V_TREADY_int_regslice;
wire    regslice_both_output3_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg = 1'b0;
#0 grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg = 1'b0;
end

config_parser_v1_buffer_V #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
v1_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(v1_buffer_V_address0),
    .ce0(v1_buffer_V_ce0),
    .we0(v1_buffer_V_we0),
    .d0(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_d0),
    .q0(v1_buffer_V_q0)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_207_1 grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_ready),
    .input1_V_TVALID(input1_V_TVALID_int_regslice),
    .config_num(config_num_reg_152),
    .input1_V_TDATA(input1_V_TDATA_int_regslice),
    .input1_V_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_input1_V_TREADY),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_ce0),
    .v1_buffer_V_we0(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_we0),
    .v1_buffer_V_d0(grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_d0)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_213_2 grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_ready),
    .output1_V_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TREADY),
    .config_num(config_num_reg_152),
    .v1_buffer_V_address0(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_address0),
    .v1_buffer_V_ce0(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_ce0),
    .v1_buffer_V_q0(v1_buffer_V_q0),
    .output1_V_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TDATA),
    .output1_V_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TVALID)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_221_3 grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_ready),
    .output3_V_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TREADY),
    .config_num(config_num_reg_152),
    .output3_V_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TDATA),
    .output3_V_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TVALID)
);

config_parser_config_parser_Pipeline_VITIS_LOOP_230_5 grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start),
    .ap_done(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_done),
    .ap_idle(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_idle),
    .ap_ready(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_ready),
    .output2_V_TREADY(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TREADY),
    .tmp_3(tmp_reg_191),
    .output2_V_TDATA(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TDATA),
    .output2_V_TVALID(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TVALID)
);

config_parser_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input1_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input1_V_TDATA),
    .vld_in(input1_V_TVALID),
    .ack_in(regslice_both_input1_V_U_ack_in),
    .data_out(input1_V_TDATA_int_regslice),
    .vld_out(input1_V_TVALID_int_regslice),
    .ack_out(input1_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_input1_V_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 512 ))
regslice_both_input2_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input2_V_TDATA),
    .vld_in(input2_V_TVALID),
    .ack_in(regslice_both_input2_V_U_ack_in),
    .data_out(input2_V_TDATA_int_regslice),
    .vld_out(input2_V_TVALID_int_regslice),
    .ack_out(input2_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_input2_V_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output1_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TDATA),
    .vld_in(grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TVALID),
    .ack_in(output1_V_TREADY_int_regslice),
    .data_out(output1_V_TDATA),
    .vld_out(regslice_both_output1_V_U_vld_out),
    .ack_out(output1_V_TREADY),
    .apdone_blk(regslice_both_output1_V_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output2_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TDATA),
    .vld_in(grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TVALID),
    .ack_in(output2_V_TREADY_int_regslice),
    .data_out(output2_V_TDATA),
    .vld_out(regslice_both_output2_V_U_vld_out),
    .ack_out(output2_V_TREADY),
    .apdone_blk(regslice_both_output2_V_U_apdone_blk)
);

config_parser_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output3_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output3_V_TDATA_int_regslice),
    .vld_in(output3_V_TVALID_int_regslice),
    .ack_in(output3_V_TREADY_int_regslice),
    .data_out(output3_V_TDATA),
    .vld_out(regslice_both_output3_V_U_vld_out),
    .ack_out(output3_V_TREADY),
    .apdone_blk(regslice_both_output3_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_ready == 1'b1)) begin
            grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        i_fu_54 <= 32'd0;
    end else if ((~((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0)) & (icmp_ln227_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        i_fu_54 <= i_4_fu_141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        config_num_reg_152 <= config_num_fu_107_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        data_num_reg_161 <= data_num_fu_111_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln227_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        tmp_reg_191 <= input2_V_TDATA_int_regslice;
    end
end

always @ (*) begin
    if ((output3_V_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_output3_V_U_apdone_blk == 1'b1) | (regslice_both_output2_V_U_apdone_blk == 1'b1) | (regslice_both_output1_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((input1_V_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input1_V_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output3_V_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output3_V_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_output3_V_U_apdone_blk == 1'b1) | (regslice_both_output2_V_U_apdone_blk == 1'b1) | (regslice_both_output1_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_output3_V_U_apdone_blk == 1'b1) | (regslice_both_output2_V_U_apdone_blk == 1'b1) | (regslice_both_output1_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        input1_V_TDATA_blk_n = input1_V_TVALID_int_regslice;
    end else begin
        input1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((input1_V_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | (~((input1_V_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input1_V_TREADY_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input1_V_TREADY_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_input1_V_TREADY;
    end else begin
        input1_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln227_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        input2_V_TDATA_blk_n = input2_V_TVALID_int_regslice;
    end else begin
        input2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0)) & (icmp_ln227_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        input2_V_TREADY_int_regslice = 1'b1;
    end else begin
        input2_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        output3_V_TDATA_blk_n = output3_V_TREADY_int_regslice;
    end else begin
        output3_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        output3_V_TDATA_int_regslice = zext_ln316_1_fu_129_p1;
    end else if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        output3_V_TDATA_int_regslice = zext_ln316_fu_120_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) & (grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TVALID == 1'b1))) begin
        output3_V_TDATA_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TDATA;
    end else begin
        output3_V_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        output3_V_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output3_V_TVALID_int_regslice = grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TVALID;
    end else begin
        output3_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v1_buffer_V_address0 = grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_address0;
    end else begin
        v1_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_v1_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        v1_buffer_V_ce0 = grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_ce0;
    end else begin
        v1_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        v1_buffer_V_we0 = grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_v1_buffer_V_we0;
    end else begin
        v1_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((input1_V_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln207_fu_115_p2 == 1'd1) & (input1_V_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((icmp_ln207_fu_115_p2 == 1'd0) & (input1_V_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((output3_V_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if ((~((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0)) & (icmp_ln227_fu_136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if ((~((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0)) & (icmp_ln227_fu_136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if ((~((regslice_both_output3_V_U_apdone_blk == 1'b1) | (regslice_both_output2_V_U_apdone_blk == 1'b1) | (regslice_both_output1_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((input1_V_TVALID_int_regslice == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state14 = ((icmp_ln227_fu_136_p2 == 1'd0) & (input2_V_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state17 = ((regslice_both_output3_V_U_apdone_blk == 1'b1) | (regslice_both_output2_V_U_apdone_blk == 1'b1) | (regslice_both_output1_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign config_num_fu_107_p1 = input1_V_TDATA_int_regslice[31:0];

assign data_num_fu_111_p1 = input1_V_TDATA_int_regslice[31:0];

assign grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_207_1_fu_77_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_213_2_fu_85_output1_V_TREADY = (output1_V_TREADY_int_regslice & ap_CS_fsm_state7);

assign grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_221_3_fu_93_output3_V_TREADY = (output3_V_TREADY_int_regslice & ap_CS_fsm_state12);

assign grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start = grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_ap_start_reg;

assign grp_config_parser_Pipeline_VITIS_LOOP_230_5_fu_100_output2_V_TREADY = (output2_V_TREADY_int_regslice & ap_CS_fsm_state16);

assign i_4_fu_141_p2 = (i_fu_54 + 32'd1);

assign icmp_ln207_fu_115_p2 = ((config_num_reg_152 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_136_p2 = ((i_fu_54 == data_num_reg_161) ? 1'b1 : 1'b0);

assign input1_V_TREADY = regslice_both_input1_V_U_ack_in;

assign input2_V_TREADY = regslice_both_input2_V_U_ack_in;

assign output1_V_TVALID = regslice_both_output1_V_U_vld_out;

assign output2_V_TVALID = regslice_both_output2_V_U_vld_out;

assign output3_V_TVALID = regslice_both_output3_V_U_vld_out;

assign zext_ln316_1_fu_129_p1 = data_num_reg_161;

assign zext_ln316_fu_120_p1 = config_num_reg_152;

endmodule //config_parser
