# This file was automatically generated by vpl
set_param project.loadTopLevelOOCConstrs 1
set_param compiler.enablePerformanceTrace true
set_param project.writeIntermediateCheckpoints 0
set_param bd.ForceAppCoreUpgrade 1
set_param board.repoPaths .local/hw_platform/board
set_param hd.Visual 0
set_param project.enablePRFlowIPI 1
set_param project.gatelevelSubdesign 1
set_param place.ultrathreadsUsed 0

# Params added by user
