# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  source ./scripts/vpl_init.tcl
  source ./scripts/ocl_util.tcl
  source ./scripts/platform.tcl
  source ./scripts/debug_profile_hooks.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}


ocl_util::report_utilization_drc "luts 269074 brams 912 registers 537219 dsps 2520" "pfm_top_i/dynamic_region" 0.8 $steps_log $vivado_output_dir
