report_utilization -file ./p_2.rpt -pblocks p_2
report_utilization -file ./p_3.rpt -pblocks p_3
report_utilization -file ./p_4.rpt -pblocks p_4
report_utilization -file ./p_5.rpt -pblocks p_5
report_utilization -file ./p_6.rpt -pblocks p_6
report_utilization -file ./p_7.rpt -pblocks p_7
report_utilization -file ./p_8.rpt -pblocks p_8
report_utilization -file ./p_9.rpt -pblocks p_9
report_utilization -file ./p_10.rpt -pblocks p_10
report_utilization -file ./p_11.rpt -pblocks p_11
report_utilization -file ./p_12.rpt -pblocks p_12
report_utilization -file ./p_13.rpt -pblocks p_13
report_utilization -file ./p_14.rpt -pblocks p_14
report_utilization -file ./p_15.rpt -pblocks p_15
report_utilization -file ./p_16.rpt -pblocks p_16
report_utilization -file ./p_17.rpt -pblocks p_17
report_utilization -file ./p_18.rpt -pblocks p_18
report_utilization -file ./p_19.rpt -pblocks p_19
report_utilization -file ./p_20.rpt -pblocks p_20
report_utilization -file ./p_21.rpt -pblocks p_21
report_utilization -file ./p_22.rpt -pblocks p_22
report_utilization -file ./p_23.rpt -pblocks p_23
report_utilization -file ./p_24.rpt -pblocks p_24
report_utilization -file ./p_25.rpt -pblocks p_25
report_utilization -file ./p_26.rpt -pblocks p_26
report_utilization -file ./p_27.rpt -pblocks p_27
report_utilization -file ./p_28.rpt -pblocks p_28
report_utilization -file ./p_29.rpt -pblocks p_29
report_utilization -file ./p_30.rpt -pblocks p_30
report_utilization -file ./p_31.rpt -pblocks p_31
report_utilization -file ./net0.rpt -pblocks net0
report_utilization -file ./net1.rpt -pblocks net1
report_utilization -file ./net2.rpt -pblocks net2
report_utilization -file ./net3.rpt -pblocks net3
report_utilization -file ./net4.rpt -pblocks net4
report_utilization -file ./net5.rpt -pblocks net5
report_utilization -file ./axi_leaf.rpt -pblocks axi_leaf
