# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  source ./scripts/vpl_init.tcl
  source ./scripts/ocl_util.tcl
  source ./scripts/platform.tcl
  source ./scripts/debug_profile_hooks.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}


set xocc_optimize_level 0
set_property SEVERITY {Warning} [get_drc_checks HDPR-5]
set_param logicopt.enableBUFGinsertHFN 0

