# This file automatically generated by vpl
# please do not modify
set vpp_link_root [file normalize [file join [file dirname [info script]] .. .. ..]]
set vpl_root "$vpp_link_root/vivado/vpl"
set local_dir "$vpl_root/.local"

set vivado_error_file "vivado_error.txt"
set vivado_warn_file "vivado_warning.txt"
set vivado_output_dir "$vpl_root/output"
set output_dir "$vpl_root/output"
set vpl_output_dir "$vpp_link_root/int"
set input_dir "$vpl_root/input"
set steps_log "$vpp_link_root/link.steps.log"
